#!/bin/bash
ln -sf ~/settings/bashprompt ~/.bashprompt
ln -sf ~/settings/aliases ~/.aliases
ln -sf ~/settings/vimrc ~/.vimrc
ln -sf ~/settings/bin ~/bin

ln -sf ~/settings/launchagents/uk.co.thirstybear.deleteoldfiles.plist ~/Library/LaunchAgents/

